# Generated by Django 4.2.7 on 2023-12-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goverb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.TextField()),
                ('forms', models.TextField()),
                ('freq', models.IntegerField(default=1)),
            ],
        ),
    ]
