# Generated by Django 4.2.7 on 2023-12-26 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goverb', '0002_verb'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first', models.BooleanField(default=False)),
                ('hint', models.PositiveIntegerField(default=0)),
                ('repeat', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verb_score', to=settings.AUTH_USER_MODEL)),
                ('verb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='goverb.verb')),
            ],
        ),
    ]
