# Generated by Django 4.2.7 on 2023-12-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goverb', '0003_verbscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbscore',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
