# Generated by Django 4.2.7 on 2023-12-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goverb', '0004_alter_verbscore_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verbscore',
            options={'ordering': ['-repeat']},
        ),
    ]
