# Generated by Django 4.2.7 on 2023-11-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_wathclist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wathclist',
            new_name='Watchlist',
        ),
    ]
