# Generated by Django 4.2.7 on 2023-11-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_watchlist_item_remove_watchlist_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
